changelog:
  categories:
    - title: 🏕 Features
      labels:
        - feature-release
    - title: 🛠 BugFix
      labels:
        - bug-release
    - title: Other Changes
      labels:
        - "*"
