name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature-release'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug-release'
      
  - title: 'Others Changes'
    labels:
      - '*'
      
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
template: |
  ## Changes

  $CHANGES
  
  
autolabeler:
  - label: 'bug'
    branch:
      - 'fix\/.+/'
  - label: 'feature'
    branch:
      - 'feature\/.+/'
